facter: do not use dummy package instantiation on windows
puppetlabs/puppetlabs-stdlib pull request #1268
Opened 2022-10-04 18:16 UTC by rismoney

2022-10-04 18:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-stdlib?pullRequest=1268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-stdlib?pullRequest=1268) before we can accept your contribution.<br/><hr/>**Rich Siegel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-stdlib?pullRequest=1268) it.</sub>

2022-10-04 18:25 UTC, bastelfreak commented
can you explain why you propose this change?

2022-10-04 18:55 UTC, rismoney commented
I believe (still reviewing) that this dummy package instantiation is causing excessive delays when run over a winrm connection.
The answer is always 'windows' as I don't believe you can change the package provider on windows before facter runs.
Here is what I see using facter -p --timing:
fact 'package_provider', took: (16.278307) seconds
when every other fact is sub-second.

2022-10-04 18:55 UTC, rismoney commented
not sure if I put this in the right spot.
https://tickets.puppetlabs.com/browse/PUP-11647?filter=-2

2022-10-04 18:59 UTC, bastelfreak commented
maybe it is worth investigating why ot takes so long (if that is always the cas). I know that many people use chololatey on windows, but I am not sure if people set that as default provider.

2022-10-04 19:18 UTC, rismoney commented
you can't set the default provider to chocolatey before puppet runs.  If you set Package {provider=chocolatey} that occurs after facter.  so I am not sure what this fact accomplishes on windows. Personally i think the fact is a bit 'dumb', as it only confirms what puppet already knew.

2022-10-04 20:47 UTC, rismoney commented
>  custom provider, like the chocolety one, could overwrite the default provider that puppet core sets.

Can you substantiate that?  If that is the case, I will abandon this effort.

2022-10-17 09:35 UTC, jordanbreen28 commented
Hi @rismoney - as you have noted, a custom provider cannot override the default. It can claim to be default and then Puppet will "randomly" choose one and warn you about it. 

Unfortunately, there seems to be test failures for this PR - could you look to resolve them and then rebase with the current main so we can proceed? :-)

2022-10-17 09:54 UTC, ekohl requested changes

2022-10-17 09:54 UTC, ekohl commented on lib/facter/package_provider.rb
> +  end
You can even use weights. It still works on Windows so just give this a weight of 50:
```suggestion
  has_weight 50
```

2022-10-17 09:54 UTC, ekohl commented on lib/facter/package_provider.rb
> +  end
And then give this a higher weight (like 100) and confine it to windows.
```suggestion
  has_weight 100
  confine kernel: 'windows'
```

2022-10-17 09:54 UTC, ekohl commented on lib/facter/package_provider.rb
> +
In our coding style we don't have this empty line after a `do` block starts.
```suggestion
```

2022-10-17 09:54 UTC, ekohl commented on lib/facter/package_provider.rb
> +
```suggestion
```

2022-10-17 09:54 UTC, ekohl commented on spec/unit/facter/package_provider_spec.rb
> +
```suggestion
```

2022-11-14 10:09 UTC, jordanbreen28 commented
Hi @rismoney,
As there has been no movement on this PR since October 4th, I will proceed to close this request.
Once you have the bandwidth to pick this back up again, and review the comments above, please do re-open this request and we can think about proceeding!
Thanks for your continued hard work on this!

2022-11-14 10:09 UTC, closed without merging