stdlib::ensure: update function to spport the generic case
puppetlabs/puppetlabs-stdlib pull request #1286
Opened 2022-12-09 12:12 UTC by b4ldr

Often custom resources only support present/absent for the ensure parameter and often the inclusion of theses resources are enabled via some boolean value as such i often find my self using the following pattern

```puppet
$ensure_feature = $enable_feature.bool2str('ensure', 'present')
```

This patch updates the stdlib::ensure function so we can simplify this to

```puppet
$ensure_feature = $enable_feature.stdlib::ensure   # or ...
$ensure_feature = stdlib::ensure($enable_feature)  # or ...
$ensure_feature = stdlib::ensure($enable_feature, 'present')
```

2022-12-09 16:45 UTC, ekohl requested changes

2022-12-09 16:45 UTC, ekohl commented on spec/functions/stdlib_ensure_spec.rb
> +  context 'work with generi resource' do
```suggestion
  context 'work with generic resource' do
```

2022-12-09 16:45 UTC, ekohl commented on functions/ensure.pp
> +  Enum['present', 'directory', 'link', 'mounted', 'service', 'file', 'package'] $resource = 'present',
I don't think there is a resource type named `present`. If you want to make it optional, then perhaps it should be made `undef` and caught as an `undef` in the case statement.
```suggestion
  Optional[Enum['present', 'directory', 'link', 'mounted', 'service', 'file', 'package']] $resource = undef,
```

2022-12-14 10:40 UTC, ekohl approved these changes
Would you mind squashing the commits?

I'd also appreciate if someone else took a look since I suggested the implementation.

2022-12-14 10:40 UTC, ekohl commented on spec/functions/stdlib_ensure_spec.rb
> +  context 'work with generic resource' do
```suggestion
  context 'work without resource' do
```

2022-12-14 11:50 UTC, b4ldr commented
> Would you mind squashing the commits?

done

> I'd also appreciate if someone else took a look since I suggested the implementation.

sure no rush my end

2022-12-14 18:31 UTC, kenyon requested changes
Would be good to fix the typo in the PR title and commit message, `spport` :)

2022-12-15 13:18 UTC, b4ldr commented
> Would be good to fix the typo in the PR title and commit message, `spport` :)

done

2022-12-16 18:17 UTC, kenyon approved these changes

2022-12-16 18:30 UTC, ekohl approved these changes
In this repository Puppet's module team needs to approve before it can be merged.

2022-12-19 16:22 UTC, LukasAud approved these changes
LGTM

2022-12-19 16:22 UTC, merged