[CAT-1382] : Fixing CI failure due to rubocop
puppetlabs/puppetlabs-stdlib pull request #1395
Opened 2023-09-11 09:23 UTC by rajat-puppet

## Summary
Fixing CI failure due to rubocop

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

2023-09-11 09:27 UTC, ekohl requested changes

2023-09-11 09:27 UTC, ekohl commented on .rubocop_todo.yml
>      - 'spec/unit/puppet/provider/file_line/ruby_spec_use_cases.rb'
Please fix these instead by renaming the files. They are tests that don't get executed.

2023-09-12 08:32 UTC, Ramesh7 approved these changes

2023-09-12 10:43 UTC, ekohl approved these changes
RuboCop changes look good. Thanks for fixing it the proper way.

2023-09-12 10:43 UTC, merged