Revert "(CONT-801) Deprecate uriescape.rb"
puppetlabs/puppetlabs-stdlib pull request #1402
Opened 2023-10-17 13:13 UTC by traylenator

This reverts commit 799d608939b90effb7cfa7d0054a3985c78db982.

While uriescape was deprecated for Puppet 8 in https://github.com/puppetlabs/puppetlabs-stdlib/pull/1307 it was already fixed earlier for Puppet 8 and ruby 3 in https://github.com/puppetlabs/puppetlabs-stdlib/pull/1195

It is unclear to me why this function was deprecated.

* Fixes #1401

## Summary
Provide a detailed description of all the changes present in this pull request.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
- [ ] Thought process behind the implementation.

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [x ] 🟢 Spec tests.
- [x ] 🟢 Acceptance tests.
- [x ] Manually verified. (For example `puppet apply`)

2023-10-17 13:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-stdlib?pullRequest=1402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-stdlib?pullRequest=1402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-stdlib?pullRequest=1402) it.</sub>

2023-10-17 13:15 UTC, traylenator commented
CLA signed in agreement between CERN IT and Puppetlabs.

2023-10-17 13:21 UTC, ekohl requested changes
In case that we do proceed with this: you need to update the comments on line 6 & 7.

On the question if we should proceed: I'm not sure if this is a good idea, I don't know. there's a good reason it was dropped in Ruby 3: the whole idea behind the function is sketchy. I'm more a fan of explicit URL construction where you pass the parameters unescaped and then it correctly constructs the URL.

2023-10-17 15:00 UTC, ekohl requested changes

2023-10-17 15:00 UTC, ekohl commented on spec/functions/uriescape_spec.rb
Looks like lines 6 & 7 in this file also need to be dropped.

2023-10-17 15:00 UTC, traylenator commented
Redundant comments removed.

I only use it one place to escape `PS Scavenge` and `PS MarkSweep` before we pass them as parameters to a
puppetserver beans endpoint.

`java.lang:name=PS%20Scavenge` 

when pulling metrics out of PuppetServer.

Does a url from component function exist ?

2023-10-17 15:03 UTC, ekohl commented
https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string suggests `URI.encode_www_form_component` would be the proper replacement. It only escapes a URL parameter

2026-09-04 17:15 UTC, jst-cyr commented
@traylenator : Is this change still needed? The function was deprecated quite some time ago and now we're onto Puppet Core 9 with Ruby 4, I'm wondering if we can possibly close this out?

Just in case, did a rebase to double-check we are still green on Puppet 8 spec tests.

2026-09-04 18:58 UTC, traylenator commented
It's so long ago. If I ever cared about this I will have worked around it since them.

Thanks for chasing up this stuff .

Steve

2026-09-04 18:58 UTC, closed without merging