Use the read method on the return of open_url to actually get the con…
puppetlabs/puppetlabs-stdlib pull request #1420
Opened 2024-03-05 17:47 UTC by gerases

## Summary
Use the read method on the return of open_url to actually get the content. Otherwise the following error is returned by puppetserver:

```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call,
 no implicit conversion of Tempfile into String (file: <file_path>, line: 8, column: 15) on node <node_name>
```

2024-03-05 17:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-stdlib?pullRequest=1420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-stdlib?pullRequest=1420) before we can accept your contribution.<br/><hr/>**Sergei Gerasenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-stdlib?pullRequest=1420) it.</sub>

2024-03-14 02:08 UTC, smortex requested changes
The test suite needs to be adjusted accordingly.  Currently it assumes `OpenURI.open_uri` return a `String` but in reality it return a `StringIO` or a `Tempfile` depending on the response. And both have a `read` method.

I am not found of doubles, but something like:

```diff
diff --git a/spec/functions/loadjson_spec.rb b/spec/functions/loadjson_spec.rb
index 17d01e45..0022ebfa 100644
--- a/spec/functions/loadjson_spec.rb
+++ b/spec/functions/loadjson_spec.rb
@@ -98,7 +98,9 @@ describe 'loadjson' do
       let(:json) { '{"key":"value", {"ķęŷ":"νậŀųề" }, {"キー":"値" }' }
 
       it {
-        expect(OpenURI).to receive(:open_uri).with(filename, {}).and_return(json)
+        data = double
+        expect(data).to receive(:read).and_return(json)
+        expect(OpenURI).to receive(:open_uri).with(filename, {}).and_return(data)
         if Puppet::PUPPETVERSION[0].to_i < 8
           expect(PSON).to receive(:load).with(json).and_return(data).once
         else
```

Run `bundle exec rake spec` to run the test suite on your machine.  Failures are reported here:

* `./spec/functions/loadjson_spec.rb:100`
* `./spec/functions/loadjson_spec.rb:120`
* `./spec/functions/loadjson_spec.rb:140`
* `./spec/functions/loadjson_spec.rb:157`

2024-03-14 18:35 UTC, smortex commented
> Yep, will do within a few days, thank you.
Thanks!

> Do you agree it's a bug though?
Yup!

2024-03-15 04:47 UTC, gerases commented
@smortex, I decided to use StringIO in the tests. I'm not sure how to restart the build though.

2024-03-15 14:45 UTC, gerases commented
Also I see there's no way to test using a docker image, which is a bit of a hassle. Is there a plan to add that similar to other repos of vox pupuli? By the way, why "pupuli" (which is incorrect) and not "populi"?

2024-03-15 17:06 UTC, bastelfreak commented
@gerases puppetlabs/stdlib uses Litmus to spin up SUTs (systems under test), whereas Vox Pupuli uses Beaker. But as Beaker, Litmus supports Docker (and Podman I think?) Containers for SUTs. I just don't know how to use Litmus.

And Vox Pupuli is correct, it's just not 'people', but 'puppet': https://latin-dictionary.net/search/english/puppet

2024-03-15 17:12 UTC, gerases commented
> And Vox Pupuli is correct, it's just not 'people', but 'puppet': https://latin-dictionary.net/search/english/puppet

Oh, fantastic then. Didn't think of "pupulus". Thanks.

2024-03-15 20:28 UTC, smortex approved these changes
LGTM!

2024-04-04 21:37 UTC, gerases commented
@bastelfreak  Could this be merged?

2024-04-04 21:42 UTC, bastelfreak commented
I'm a bit hesitant on merging because I don't know if this change breaks the setup for other users. I need to test it and I currently don't have the time.

2024-04-05 11:18 UTC, ekohl commented
I'm surprised I didn't link it, but https://github.com/puppetlabs/puppetlabs-stdlib/pull/1415 was my attempt to address it.

2026-09-04 16:41 UTC, jst-cyr commented
I did a rebase to run this through the tests again with the latest main updates (similar to #1415).  It looks like there was a general consensus that this was a bug but that folks were unsure how much this might break setups. 

@gerases : Is this still a need in your setup?

2026-09-18 14:49 UTC, jst-cyr commented
Closing this PR for now until a need rises for this in the future at which point we can re-open!

2026-09-18 14:49 UTC, closed without merging

2026-09-18 15:24 UTC, gerases commented
Sorry missed your ping, I'm not sure how much it is a problem, was just trying to contribute, i think it's pretty safe to merge, but who am i to say :)

2026-09-18 18:36 UTC, jst-cyr commented
Hey, no worries, @gerases ! I don't mind reopening if this is still something that people need resolved. I do see #1460 also open that seems to have some similar overlap. Do you mind taking a look at #1460 and seeing if we could centralize on that PR as the place for us to address this issue? Between @smortex and yourself, we might be able to get a solid fix here between both your attempts.